[package]
name = "ftp-client"
version = "0.1.2"
authors = ["Adilson Neto <almeidneto@gmail.com>"]
edition = "2021"
readme = "README.md"

keywords = ["ftp"]
categories = ["network-programming"]
description = "A FTP client library"
repository = "https://github.com/aaneto/ftp-client"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-error = "0"
native-tls = "0"
tokio = { version = "0.2", features = ["tcp", "io-util"] }
tokio-tls = "0.3"
log = "0"

[dev-dependencies]
once_cell = "1"
